### ISSUE TITLE
1122 todo

### ISSUE THREAD

**Issue by neoddish** [antvis/AVA#84]
- [x] custom rules
- [x] chart-advisor new pipeline and api
- [x] plot types +
- [x] autoChart config panel
- [x] test cases & coverage
- [ ] pkg: datasample
- [ ] pkg: thumbnails
- [x] docs
- [x] demos
- [x] promo articles

**Comment by jiazhewang** [comment]
chart type priority:

P0:

- [ ] Line
- [ ] Area
- [ ] Column
- [ ] Bar
- [ ] Pie
- [ ] Scatter
- [ ] Histogram
- [ ] Heatmap

P1:

- [ ] Radar
- [ ] DualAxes
- [ ] Box
- [ ] Waterfall
- [ ] BidirectionBar

P2:

- [ ] Rose
- [ ] WordCloud
- [ ] Progress
- [ ] RingProgress
- [ ] Funnel
- [ ] Bullet
- [ ] Sunburst
- [ ] RadialBar

P3:

- [ ] TinyLine
- [ ] TinyColumn
- [ ] TinyArea
- [ ] Stock
- [ ] Liquid
- [ ] Gauge

@Esorakouki
